package di.aittr.pro_sotrudnikov.exeption_handling.handling.exeptions;

public class ZadacaValidacionExeption extends RuntimeException {

    public ZadacaValidacionExeption(Throwable cause) {
        super(cause);
    }
}
